### ISSUE TITLE
How to create a lcov base

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vebr/jest-lcov-reporter#12]
In the readme:

> lcov-base (Optional)
The location of the lcov file resulting from running the tests in the base branch. When this is set a diff of the coverage percentages is shown.

**How to create this lcov base from the master/main branch?** I could create it myself every time and commit it, but i don't think that's a good idee? 

Should there be an actions that runs the test every time on the master and store this somehow?
Or should this action also run tests on another branch? is that possible?

**Comment by vebr** [comment]
Hello @ricardovanlaarhoven I think you can set another action to pull your master/main branch and start the test there, hope this help [https://github.com/actions/checkout#Checkout-a-different-branch](https://github.com/actions/checkout#Checkout-a-different-branch)
